### ISSUE TITLE
Get value of the rule parameter

### ISSUE THREAD

**Issue by Melchyore** [adonisjs/adonis-validation-provider#53] opened 2018-05-25 22:26 UTC
It would be useful if we can get the value of the parameter of a given rule.
Let say we have something like that :
```json
{
  "_default": "Field {field} is not valid.",
  "min": "Field {field} must contain at least {min} character(s)."
}
```

```js
get rules () {
  return {
    username: 'required|min:3|max:15|unique:users,username',
    email: 'required|email|max:30|unique:users,email',
    password: 'required|min:6|max:60'
  }
}

async fails (errorMessages) {
    let error = errorMessages[0] // Remove that if validateAll returns true.
    let messageData = {
      field: error.field
    }

    messageData[error.validation] = error.rule // <-- Notice here the new property. It should print of course 3 because "min:3" if there's a min error.

    return this.ctx.response.send({
      field: error.field,
      message: Antl.formatMessage(`validation.${error.validation ? error.validation : '_default'}`, messageData)
    })
  }
```

What do you think about that?

**Comment by thetutlage** [comment] 2018-05-28 03:29
It's supported, check here https://indicative.adonisjs.com/docs/templating#_available_keywords

**Comment by Melchyore** [comment] 2018-05-28 21:30
Thank you!
locales/en/validation.json :
```json
{
  "_default": "Field {field} is not valid.",
  "min": "Field {field} must contain at least {argument.0} character(s)."
}
```
But how I can provide the 'argument' array automaticaly here : 
Validators/StoreUser.js
```js
async fails (errorMessages) {
  const antl = this.ctx.antl

  let error = errorMessages[0] // Remove that if validateAll returns true.
  let rule = error.validation

  if (rule === 'ENGINE_EXCEPTION') {
    return this.ctx.response.serverError(antl.get('errors.500'))
  }

  return this.ctx.response.badRequest({
    field: error.field,
    message: antl.formatMessage(`validation.${rule ? rule : '_default'}`, {
      field: error.field
    })
  })
}
```
please?

Or it must be added manually?

The objects inside errorMessages array don't contain any 'argument' property.

**Comment by thetutlage** [comment] 2018-05-29 02:39
You don't have to pass it. It will be injected automatically by indicative. Your message will look as follows.

```
{
  "min": "Field {{ field }} must contain at least {{ argument.0 }} character(s)."
}
```

The double curly brace `{{` will not be parsed by `antl` and hence forwarded to indicative.

**Comment by Melchyore** [comment] 2018-05-29 15:12
Thanks!

But it doesn't seem to work or I did something wrong.

When I try using `formatMessage` or `get` :
```js
antl.formatMessage(`validation.${rule ? rule : '_default'}`, {
  field: error.field
}) // Returns empty string

antl.formatMessage(`validation.${rule ? rule : '_default'}`) // Returns empty string

antl.get(`validation.${rule ? rule : '_default'}`) // Returns string not parsed, i.e : Field {{ field }} must contain at least {{ argument.0 }} character(s).
```

Maybe I don't get the way to achieve it?
(sorry to be hassle)

**Comment by thetutlage** [comment] 2018-05-31 05:44
So the problem is, you are not using the inbuilt messages property of the validator and making messages yourself. In that case, it is expected that no transformation of values will be done.

What you need is simple

```js
get messages () {
  min: this.ctx.antl.formatMessage('validation.min')
}
```

**Comment by Melchyore** [comment] 2018-05-31 15:38
Thanks, it works now!
(it was not mentioned in the docs :p)

Also, is it possible to do something like that :
```js
get fields () {
  return {
    username: 'pseudo'
  }
}
```
so that indicative will replace {{ field }} by the new field value.

**Comment by thetutlage** [comment] 2018-06-01 11:21
Nope, that's not possible and also not something I am planning to add

**Closed as completed by thetutlage** 2018-06-01 11:21 UTC

**Comment by papalardo** [comment] 2019-04-17 18:32
> Thanks, it works now!
> (it was not mentioned in the docs :p)
> 
> Also, is it possible to do something like that :
> 
> ```js
> get fields () {
>   return {
>     username: 'pseudo'
>   }
> }
> ```
> 
> so that indicative will replace {{ field }} by the new field value.

I try here and not working. 😢
