### ISSUE TITLE
The class name invalid when generate Validator file using command

### ISSUE THREAD

**Issue by trantuan94** [adonisjs/adonis-validation-provider#65] opened 2019-06-27 02:04 UTC
## Package version

v5.0.9
## Node.js and npm version

Node v10.16.0
npm v6.9.0
OS: Ubuntu 18.04 LTS
## Description
I installed your package into my Adonisjs project and also tried to generate Validator file by your command. But I still detect this bug. The 'adonis make:validator  User/CreateUser' command create the new file in ./Validators/User/CreateUser.js but the 'class name' still invalid -UserCreateUser.

**Comment by RomainLanz** [comment] 2019-06-30 07:42
Hey @trantuan94! 👋 

Since this code is tested in our package could you please make a falling test so we can reproduce the issue?

**Comment by thetutlage** [comment] 2020-02-14 08:18
Closing since it not valid anymore

**Closed as completed by thetutlage** 2020-02-14 08:18 UTC
Labels: Type: Bug, Semver: Major, Priority: Medium
